version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

  automessage:
    image: automessage
    ports:
      - 80:80
    volumes:
      - .env:/var/www/html/automessage-stage/.env